---
  - name: Install IUS repo.
    yum:
      lock_timeout: 180 # wait up to 3 minutes for a lock ansible/ansible#57189
      name:
        - https://repo.ius.io/ius-release-el7.rpm \
        - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

  - name: Import IUS Community Project GPG key
    rpm_key:
      key: https://repo.ius.io/RPM-GPG-KEY-IUS-7
      state: present
