---
- name: Install IUS repo.
  yum:
    lock_timeout: 180 # wait up to 3 minutes for a lock ansible/ansible#57189
    name: "https://repo.ius.io/ius-release-el{{ ansible_distribution_major_version }}.rpm"

- name: Import IUS Community Project GPG key
  rpm_key:
    key: http://dl.iuscommunity.org/pub/ius/IUS-COMMUNITY-GPG-KEY
    state: present
