---
- name: Remove IUS Repo since we're at distro 8+
  package:
    name: "ius-release"
    state: absent

- name: Remove PHP 5.x packages
  package:
    lock_timeout: 180 # wait up to 3 minutes for a lock ansible/ansible#57189
    name: "php5*"
    state: absent

- name: Ensure PHP packages for Rocky/RHEL8 installed
  package:
    name:
      - php-cli
      - php-common
      - php-devel
      - php-gd
      - php-json
      - php-snmp
      - php-xml
      - php-xmlrpc
      - php-mysqlnd
      - php-pdo
      - php-odbc
      - php-process
      - php-bcmath
      - php-intl
      - php-opcache
      - php-soap
      - php-mbstring
      - php-ldap
      - php-fpm
      - php-pear
      - libmemcached-devel
    state: present

# PHP memcached extension needed for SAML auth
- name: Ensure PEAR channel up-to-date
  shell: pear channel-update pecl.php.net

- name: Install memcached PECL packages
  shell: >
    pecl install
    --configureoptions
    'with-libmemcached-dir="no"
    with-zlib-dir="no"
    with-system-fastlz="no"
    enable-memcached-igbinary="no"
    enable-memcached-msgpack="no"
    enable-memcached-json="no"
    enable-memcached-protocol="no"
    enable-memcached-sasl="yes"
    enable-memcached-session="yes"'
    memcached
  ignore_errors: true
  notify:
    - restart apache

- template:
    src: 40-memcached.ini.j2
    dest: /etc/php.d/40-memcached.ini
    owner: root
    group: root
    mode: 0644
  notify:
  - restart apache
